# Site settings
title: On The Run Optical
email: lisa@ontherunoptical.com
url: https://billy-ran-away.github.io/on_the_run/
description: "Fast, Affordable, Accurate Optical Services"
keywords: "your keywords, separated by commas"
skills: "Fast - Affordable - Accurate"
meta_author: Transue Bill

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 258cbf #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: On The Run Optical
  location: Location
  social: Around the Web
  get_in_touch: Get In Touch

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ontherunoptical
  - title: facebook
    url: http://facebook.com/ontherunoptical

# Postal address (add as many lines as necessary)
address:
  - line: Savage Mills
  - line: 8600 Foundry St
  - line: 215-C Suite
  - line: Savage, MD 20763

# Credits content
get_in_touch: '<i class="fa fa-mobile"></i> 301-974-9003'

# Build settings
markdown: kramdown
permalink: pretty
